server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      # Автоматическое обнаружение сервисов через Eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ================== MAIN SERVICE ==================

        - id: main-admin
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: main-private
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/users/**

        - id: main-public
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=
              /categories,
              /categories/**,
              /events,
              /events/**,
              /compilations,
              /compilations/**,
              /events/*/comments,
              /events/*/comments/**

        # ================== STATS SERVICE ==================

        - id: stats
          uri: lb://STATS-SERVICE
          predicates:
            - Path=/hit, /stats


        # Роут для actuator (мониторинг)
        - id: actuator_route
          uri: lb://gateway
          predicates:
            - Path=/actuator/**

# Настройки Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Мониторинг и метрики
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Логирование
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG