server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      # Автоматическое обнаружение сервисов через Eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: main-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**

        - id: main-private
          uri: lb://main-service
          predicates:
            - Path=/users/**

        - id: main-public
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/events/**,/compilations/**,/events/*/comments/**

        - id: stats
          uri: lb://stats-service
          predicates:
            - Path=/hit,/stats

# Настройки Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Мониторинг и метрики
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

# Логирование
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG